//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class ChngMgtEntities1 : DbContext
{
    public ChngMgtEntities1()
        : base("name=ChngMgtEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Application> Applications { get; set; }
    public DbSet<Change> Changes { get; set; }
    public DbSet<Change_Comment> Change_Comment { get; set; }
    public DbSet<Change_Type> Change_Type { get; set; }
    public DbSet<ChngMgt_Access> ChngMgt_Access { get; set; }
    public DbSet<Department> Departments { get; set; }
    public DbSet<User_Request> User_Request { get; set; }
    public DbSet<User> Users { get; set; }
}
