//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Application
{
    public Application()
    {
        this.Changes = new HashSet<Change>();
        this.User_Request = new HashSet<User_Request>();
    }

    public int Application_ID { get; set; }
    public string Application1 { get; set; }

    public virtual ICollection<Change> Changes { get; set; }
    public virtual ICollection<User_Request> User_Request { get; set; }
}

public partial class Change
{
    public Change()
    {
        this.Change_Comment = new HashSet<Change_Comment>();
    }

    public int Change_ID { get; set; }
    public string Description { get; set; }
    public string Creation_Date { get; set; }
    public Nullable<System.DateTime> Last_Update { get; set; }
    public string Priotity { get; set; }
    public int Req_ID { get; set; }
    public Nullable<int> App_ID { get; set; }
    public Nullable<int> Auth_ID { get; set; }
    public Nullable<int> QA_ID { get; set; }
    public Nullable<int> Dev_ID { get; set; }
    public Nullable<int> Deplopy_ID { get; set; }
    public Nullable<int> UAT_ID { get; set; }
    public Nullable<System.DateTime> App_Date { get; set; }
    public Nullable<System.DateTime> QA_Date { get; set; }
    public string Status { get; set; }
    public int Req_Type { get; set; }
    public int Application { get; set; }
    public Nullable<int> BA_ID { get; set; }
    public Nullable<System.DateTime> BA_Date { get; set; }
    public string Summary { get; set; }
    public string Auth_Date { get; set; }
    public Nullable<int> Dev_Assign { get; set; }
    public string Dev_Assign_Date { get; set; }
    public string Dev_Date { get; set; }
    public string Deploy_Date { get; set; }
    public string UAT_Date { get; set; }

    public virtual Application Application1 { get; set; }
    public virtual User User { get; set; }
    public virtual User User1 { get; set; }
    public virtual Change_Type Change_Type { get; set; }
    public virtual ICollection<Change_Comment> Change_Comment { get; set; }
    public virtual User User2 { get; set; }
    public virtual User User3 { get; set; }
    public virtual User User4 { get; set; }
    public virtual User User5 { get; set; }
    public virtual User User6 { get; set; }
}

public partial class Change_Comment
{
    public int Comment_ID { get; set; }
    public int Change_ID { get; set; }
    public int UserID { get; set; }
    public string Comment { get; set; }
    public string Date { get; set; }

    public virtual Change Change { get; set; }
    public virtual User User { get; set; }
}

public partial class Change_Type
{
    public Change_Type()
    {
        this.Changes = new HashSet<Change>();
    }

    public int ChangeType_ID { get; set; }
    public string Type { get; set; }

    public virtual ICollection<Change> Changes { get; set; }
}

public partial class ChngMgt_Access
{
    public int Access_ID { get; set; }
    public string User_ID { get; set; }
    public string Access_Level_ID { get; set; }

    public virtual User User { get; set; }
}

public partial class Department
{
    public Department()
    {
        this.Users = new HashSet<User>();
    }

    public int Dep_ID { get; set; }
    public string Department1 { get; set; }
    public string Location { get; set; }

    public virtual ICollection<User> Users { get; set; }
}

public partial class User
{
    public User()
    {
        this.Changes = new HashSet<Change>();
        this.Changes1 = new HashSet<Change>();
        this.Changes2 = new HashSet<Change>();
        this.Changes3 = new HashSet<Change>();
        this.Changes4 = new HashSet<Change>();
        this.Changes5 = new HashSet<Change>();
        this.Changes6 = new HashSet<Change>();
        this.Change_Comment = new HashSet<Change_Comment>();
        this.User_Request = new HashSet<User_Request>();
        this.User_Request1 = new HashSet<User_Request>();
        this.User_Request2 = new HashSet<User_Request>();
        this.User_Request3 = new HashSet<User_Request>();
    }

    public int User_ID { get; set; }
    public string User_Name { get; set; }
    public Nullable<int> User_Level { get; set; }
    public Nullable<int> Department_ID { get; set; }
    public string Password { get; set; }
    public string Designation { get; set; }

    public virtual ICollection<Change> Changes { get; set; }
    public virtual ICollection<Change> Changes1 { get; set; }
    public virtual ICollection<Change> Changes2 { get; set; }
    public virtual ICollection<Change> Changes3 { get; set; }
    public virtual ICollection<Change> Changes4 { get; set; }
    public virtual ICollection<Change> Changes5 { get; set; }
    public virtual ICollection<Change> Changes6 { get; set; }
    public virtual ICollection<Change_Comment> Change_Comment { get; set; }
    public virtual ChngMgt_Access ChngMgt_Access { get; set; }
    public virtual Department Department { get; set; }
    public virtual ICollection<User_Request> User_Request { get; set; }
    public virtual ICollection<User_Request> User_Request1 { get; set; }
    public virtual ICollection<User_Request> User_Request2 { get; set; }
    public virtual ICollection<User_Request> User_Request3 { get; set; }
}

public partial class User_Request
{
    public int UserReq_ID { get; set; }
    public Nullable<int> Req_By { get; set; }
    public Nullable<System.DateTime> Req_Date { get; set; }
    public Nullable<int> Approved_By { get; set; }
    public Nullable<System.DateTime> Approved_Date { get; set; }
    public Nullable<int> Created_By { get; set; }
    public Nullable<System.DateTime> Created_Date { get; set; }
    public Nullable<int> Confirmed_By { get; set; }
    public Nullable<System.DateTime> Confirmed_Date { get; set; }
    public Nullable<int> Application_ID { get; set; }
    public string Access_level { get; set; }
    public string Comment { get; set; }
    public string Status { get; set; }

    public virtual Application Application { get; set; }
    public virtual User User { get; set; }
    public virtual User User1 { get; set; }
    public virtual User User2 { get; set; }
    public virtual User User3 { get; set; }
}
